changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - skip-release-notes
      - wontfix
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
